[general]
import = [
  "/usr/lib/node_modules/alacritty-themes/themes/Tokyonight_Night.toml"
]

[window]
opacity = 0.9

[font]
# normal = { family = "Monocraft", style = "Regular" }
# bold = { family = "Monocraft", style = "Bold" }
# italic = { family = "Monocraft", style = "Italic" }
# bold_italic = { family = "Monocraft", style = "Bold Italic" }
normal = {family = "ComicShannsMonoNerdFont", style="Regular" }
bold = {family = "ComicShannsMonoNerdFont", style="Bold" }
italic = {family = "ComicShannsMonoNerdFont", style="Italic" }
size = 12.5


